Repository ManageIQ/manageiq-loggers, pull requests merged in 2020-08, with the labels that each got.

#21 Fix the handling of journald code_file/code_line
  lib/manageiq/loggers/journald.rb
Labels: bug

#22 Add spec for journald caller_locations
  spec/manageiq/journald_spec.rb
Labels: test

#23 Add code_func
  lib/manageiq/loggers/journald.rb
Labels: enhancement
